### ISSUE TITLE
Exception when add message to idea

### ISSUE THREAD

**Issue by kamiljaszczynski** [assembl/assembl#143]
Traceback (most recent call last):
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/assembl/assembl/venv/src/sqltap/sqltap/wsgi.py", line 42, in __call__
    return self.app(environ, start_response)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 187, in toolbar_tween
    return handler(request)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 354, in _authdebug_view
    return view(context, request)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 302, in _secured_view
    return view(context, request)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/assembl/assembl/venv/src/cornice/cornice/service.py", line 573, in wrapper
    response = view_(request)
  File "/home/assembl/assembl/assembl/views/api/post.py", line 660, in create_post
    original_subject.first_original().value or ''
AttributeError: 'LangStringEntry' object has no attribute 'first_original'

Some of you had similar problem ?

**Comment by vincentfretin** [comment]
Please specify the version, branch, or commit when you write an issue.
But yeah I see in develop branch the issue, we missed this in code review. :(
I fixed it.

**Comment by vincentfretin** [comment]
Thanks for notifying us!

**Comment by kamiljaszczynski** [comment]
Thanks a loot !!

I use code that you put on develop. But there is another problem. When make
commants:
I use master:


2017-08-23 22:28:17,821 WARNI [elasticsearch][waitress] POST
http://localhost:9200/_bulk [status:400 request:0.005s]
2017-08-23 22:28:17,822 CRITI [txn.140692979705600][waitress] A storage
error occurred during the second phase of the two-phase commit.  Resources
may be in an inconsistent state.
2017-08-23 22:28:17,822 ERROR [txn.140692979705600][waitress] Error in
tpc_abort() on manager <zope.sqlalchemy.datamanager.SessionDataManager
object at 0x7ff56fad0390>
Traceback (most recent call last):
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/transaction/_transaction.py",
line 431, in _cleanup
    rm.tpc_abort(self)
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/zope/sqlalchemy/datamanager.py",
line 116, in tpc_abort
    assert self.state is not 'committed'
AssertionError
2017-08-23 22:28:17,827 ERROR [waitress][waitress] Exception when serving
/data/Discussion/3/posts/8/sentiments
Traceback (most recent call last):
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/waitress/channel.py",
line 338, in service
    task.service()
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/waitress/task.py",
line 169, in service
    self.execute()
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/waitress/task.py",
line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/assembl/assembl/venv/src/sqltap/sqltap/wsgi.py", line 42, in
__call__
    return self.app(environ, start_response)
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/router.py",
line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/router.py",
line 211, in invoke_subrequest
    response = handle_request(request)
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py",
line 187, in toolbar_tween
    return handler(request)
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/tweens.py",
line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid/tweens.py",
line 22, in excview_tween
    response = handler(request)
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py",
line 101, in tm_tween
    reraise(*exc_info)
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py",
line 90, in tm_tween
    manager.commit()
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/transaction/_manager.py",
line 123, in commit
    return self.get().commit()
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/transaction/_transaction.py",
line 280, in commit
    reraise(t, v, tb)
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/transaction/_transaction.py",
line 271, in commit
    self._commitResources()
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/transaction/_transaction.py",
line 416, in _commitResources
    reraise(t, v, tb)
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/transaction/_transaction.py",
line 398, in _commitResources
    rm.tpc_finish(self)
  File "/home/assembl/assembl/assembl/indexing/changes.py", line 180, in
tpc_finish
    raise_on_error=False)
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py",
line 194, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py",
line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions,
raise_on_exception, raise_on_error, **kwargs):
  File
"/home/assembl/assembl/venv/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py",
line 91, in _process_bulk_chunk
    raise e
RequestError: TransportError(400, u'illegal_argument_exception', u"Can't
specify parent if no parent field has been configured")
2017-08-23 22:28:17,935 DEBUG [assembl][waitress] route matched for url
http://itranger.pl:6543/static/img/emoticons/not_understand_active.svg;
route_name: '__static/', path_info:
u'/static/img/emoticons/not_understand_active.svg', pattern:
'static/*subpath', matchdict: {'subpath': (u'img', u'emoticons',
u'not_understand_active.svg')}, predicates: ''
2017-08-23 22:28:17,935 DEBUG [assembl][waitress] route matched for url
http://itranger.pl:6543/static/img/emoticons/not_understand_active.svg;
route_name: '__static/', path_info:
u'/static/img/emoticons/not_understand_active.svg', pattern:
'static/*subpath', matchdict: {'subpath': (u'img', u'emoticons',
u'not_understand_active.svg')}, predicates: ''
2017-08-23 22:28:17,935 DEBUG [assembl][waitress] debug_authorization of
url http://itranger.pl:6543/static/img/emoticons/not_understand_active.svg
(view name u'' against context <assembl.views.traversal.AppRoot object at
0x7ff56f9ba410>): Allowed (NO_PERMISSION_REQUIRED)
2017-08-23 22:28:17,935 DEBUG [assembl][waitress] debug_authorization of
url http://itranger.pl:6543/static/img/emoticons/not_understand_active.svg
(view name u'' against context <assembl.views.traversal.AppRoot object at
0x7ff56f9ba410>): Allowed (NO_PERMISSION_REQUIRED)

**Comment by vincentfretin** [comment]
You need to execute `assembl-reindex-all-contents` to create the elasticsearch index and index all contents.

**Comment by vincentfretin** [comment]
Please see https://github.com/assembl/assembl/blob/develop/doc/howtoupgrade.rst

**Comment by kamiljaszczynski** [comment]
Thanks :>

Now everything work fine :)
